CREATE TABLE IF NOT EXISTS users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    role_id INT NOT NULL DEFAULT 2,
    CONSTRAINT pk_roles FOREIGN KEY (role_id) REFERENCES roles(id)
);