CREATE TABLE IF NOT EXISTS refresh_tokens (
    id INT  AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usr FOREIGN KEY (user_id)  REFERENCES users(id) ON DELETE CASCADE
);